server:
  port: 1676

spring:
  datasource:
    url: jdbc:mysql://db1625-db1625.i.aivencloud.com:23308/db1625?ssl-mode=REQUIRED
    username: avnadmin
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    application:
      name: ts-profile-engine-1676